### PR TITLE
Update paths to CSS

### PR DESCRIPTION
**Pull request by zeehio**
Dear Christian Jung,

Thank you for providing this dashboard. As igoogle seems to be closing soon, I am trying to install and use it :-)

I am having trouble to show images and css, because there seems to be some issues with CSS paths.

For instance here 5ab614c4f41bf7f21ef65eb0a439060f1752c20e you are using dist/img/... but the dist directory does not exist.

If I have understood your intentions properly, you want to keep all the themable stuff in src/style and then link it from dist. By doing this, anyone could create its own src/mystyle directory and use it simply by changing "dist".

Following this idea, in my local installation I have used:

```
ln -s src/style dist
```

In the root of leDashboard in order to create a directory named dist that points to src/style, as I want to use the default (and only) theme.

In inc/header.php you seem to be using dist/img/favicon.ico, dist/style/css/flick/... and dist/style/screen.css.

If I am not mistaken, these paths are not consistent and they should be as follows:
- dist/img/favicon.ico --> OK
- dist/style/css/flick/... --> dist/css/flick/...
- dist/style/screen.css --> dist/css/flick/...

This pull request fixes both things. If hope I have understood your intentions, and this patch is helping. Otherwise, forgive me for wasting your time :-)

Thanks

Sergio

### CODE REVIEW

**Comment by chrisjung-dev** [comment]
Hi Sergio,

thank you for taking the research so far, but the missing directories "dist" and sub dirs is because I have not reflected the changes in the Gruntfile to the new Build paths. Sorry for that. 

The style.css in the src-directory is still a leftover. 

I will keep you up to date.

Chris

**Comment by zeehio** [comment]
Hi Chris,

Thanks for the update and the kind reply, I'll keep watching the repository as this igoogle replacement seems pretty much what I was looking for :-). Sorry, my experience with Javascript is quite limited and  I did not know about Grunt.

Feel free to close this issue, as it is not about any released version and I might confuse some readers instead of helping them.

Thanks again,

Sergio

**Comment by chrisjung-dev** [comment]
Hi Sergio,

please check out if version 0.0.3 resolves your problems.

Please note that usually the workflow at the moment requires Grunt and Node installed to create the dist-dir and files.

kind regards
Chris

**Comment by chrisjung-dev** [comment]
Please use 0.0.5 instead ;)

**Pull request closed without merging**
